services:
  ubuntu:
    build:
      context: ubuntu
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION-latest}
        - UID=${UID-1000}
        - GID=${GID-1000}
    hostname: scctdev
    volumes:
      - '../home:/home/scct:z'

  mysql:
    image: mariadb:latest
    volumes:
      - './mariadb/db:/var/lib/mysql:Z'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-password}

  mongodb:
    image: mongo:latest
    volumes:
      - './mongodb/db:/data/db:Z'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD-password}

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=${MYSQL_ROOT_USER-root}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD-password}

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD-password}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER-root}:${MONGO_ROOT_PASSWORD-password}@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
