# name: build_release
# run-name: ${{ github.actor }} is building release ${{ github.?? }}
# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code

#       - name: Add release tag to devcontainer env

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to ghcr
#         

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: user/app:latest
        
#       - name: Zip workspace
#         uses: thedoctor0/zip-release@0.7.5
#         with:
#           type: "zip"
#           path: "scct-dev-environment"
#           filename: "scct-dev-environment-${{ github.?? }}.zip"
        
#       - name: Attach zipped workspace to release
#         uses: ncipollo/release-action@v1.12.0
#         with:
#           artifacts: "scct-dev-environment-${{ github.?? }}.zip"
#           token: ${{ secrets.GITHUB_TOKEN }}